stages:
 - deploy

deploy:
 stage: deploy
 tags:
  - ubuntu
 script:
  - apt-get update
  - apt-get upgrade -y
  - apt-get install -y openssh-client
  - ssh -t kyky@tcc.tircher.be '/bin/bash deploy_scipio.sh'