stages:
 - build
 - dockerize
 - deploy

build:
 image: node
 stage: build
 tags:
  - docker
 before_script:
  - rm -rf node-modules
  - rm -f package-lock.json
 script:
  - /bin/bash scripts/build.sh
 artifacts:
  paths:
   - ./node_modules
   - ./package-lock.json
  expire_in: 1 day

dockerize:
 image: docker
 stage: dockerize
 services:
  - docker:dind
 tags:
  - docker
 script:
  - docker build . -t scipio
  - docker save scipio > scipio.tar
 artifacts:
  paths:
   - ./scipio.tar
  expire_in: 1 day

deploy:
 image: docker
 stage: deploy
 services:
  - docker:dind
 tags:
  - docker
 script:
  - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD} docker.tircher.be
  - docker load < ./scipio.tar
  - docker tag scipio docker.tircher.be/scipio
  - docker push docker.tircher.be/scipio