stages:
 - deploy

before_script:
 - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
 - eval $(ssh-agent -s)
 - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
 - mkdir -p ~/.ssh
 - chmod 700 ~/.ssh

deploy:
 stage: deploy
 tags:
  - ubuntu
 script:
  - apt-get update
  - apt-get upgrade -y
  - apt-get install -y openssh-client
  - ssh -t kyky@tcc.tircher.be '/bin/bash deploy_scipio.sh'