stages:
 - build
 - dockerize
 - deploy

build:
 stage: build
 tags:
  - ubuntu
 before_script:
  - rm -rf node-modules
  - rm -f package-lock.json
 script:
  - ./scripts/build.sh
 artifacts:
  paths:
   - node_modules
   - package-lock.json
  expire_in: 1 day

dockerize:
 stage: dockerize
 tags:
  - ubuntu
 script:
  - ./scripts/dockerize.sh
  - docker save scipio > scipio.tar
 artifacts:
  paths:
   - ./scipio.tar
  expire_in: 1 day

deploy:
 stage: deploy
 tags:
  - ubuntu
 script:
  - docker load < ./scipio.tar
  - docker tag scipio docker.tircher.be/scipio
  - docker push docker.tircher.be/scipio