stages:
 - build
 - dockerize
 - deploy

services:
 - docker:dind

build:
 image: docker.tircher.be/node_docker
 stage: build
 tags:
  - docker
 before_script:
  - rm -rf node-modules
  - rm -f package-lock.json
 script:
  - npm install
  - pushd scipio-angular
  - npm install
  - ng build --prod
  - popd
 artifacts:
  paths:
   - ./node_modules
   - ./package-lock.json
   - ./scipio-angular/dist
  expire_in: 1 day

dockerize with version:
 image: docker
 stage: dockerize
 tags:
  - docker
 only:
  - tags
 script:
  - docker build . -t docker.tircher.be/scipio:$CI_COMMIT_TAG
  - docker push docker.tircher.be/scipio:$CI_COMMIT_TAG

dockerize as latest:
 image: docker
 stage: dockerize
 tags:
  - docker
 script:
  - docker build . -t docker.tircher.be/scipio
  - docker push docker.tircher.be/scipio
 except:
  - tags

deploy:
 image: docker
 stage: deploy
 tags:
  - docker
 script:
  - echo "TODO automatic deploy on tcc server"
 only:
  - master