stages:
 - build
 - dockerize
 - deploy

services:
 - docker:dind

build:
 image: node
 stage: build
 tags:
  - docker
 before_script:
  - rm -rf node-modules
  - rm -f package-lock.json
 script:
  - npm install --verbose
 artifacts:
  paths:
   - ./node_modules
   - ./package-lock.json
  expire_in: 1 day

dockerize with version:
 image: docker
 stage: dockerize
 tags:
  - docker
 only:
  - tags
 script:
  - docker build . -t localhost:5005/scipio:$CI_COMMIT_TAG
  - docker push localhost:5005/scipio:$CI_COMMIT_TAG

dockerize as latest:
 image: docker
 stage: dockerize
 tags:
  - docker
 script:
  - docker build . -t localhost:5005/scipio:latest
  - docker push localhost:5005/scipio:latest
 except:
  - tags

deploy in development environment:
 image: ubuntu
 stage: deploy
 tags:
  - docker
 before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
 script:
  - ssh -t kyky@server.mytcc.be "~/deploy_dev_scipio_node.sh"
 environment:
  name: development
  url: https://dev.scipio.mytcc.be

deploy in production environment:
 image: ubuntu
 stage: deploy
 tags:
  - docker
 before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
 script:
  - ssh -t kyky@server.mytcc.be "~/deploy_prod_scipio_node.sh $CI_COMMIT_TAG"
 environment:
  name: production
  url: https://scipio.mytcc.be
 only:
  - tags
