stages:
 - build
 - dockerize
 - deploy

build:
 image: docker.tircher.be/node_docker
 stage: build
 tags:
  - docker
 before_script:
  - rm -rf node-modules
  - rm -f package-lock.json
 script:
  - npm install --verbose
 artifacts:
  paths:
   - ./node_modules
   - ./package-lock.json
  expire_in: 1 day

dockerize with version:
 image: docker
 stage: dockerize
 services:
  - docker:dind
 tags:
  - docker
 only:
  - tags
 script:
  - docker build . -t docker.tircher.be/scipio:$CI_COMMIT_TAG
  - docker push docker.tircher.be/scipio:$CI_COMMIT_TAG

dockerize as latest:
 image: docker
 stage: dockerize
 services:
  - docker:dind
 tags:
  - docker
 script:
  - docker build . -t docker.tircher.be/scipio:latest
  - docker push docker.tircher.be/scipio:latest
 except:
  - tags

deploy:
 image: docker
 stage: deploy
 services:
  - docker:dind
 tags:
  - docker
 script:
  - echo "TODO automatic deploy on tcc server"
 only:
  - master